# Generated by Django 5.1.7 on 2025-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
